// [AUTO-GENERATED FILE] -> Do not modify

allMcNames = {
    "0": "Tubarão (SP)", 
    "1": "Jhony (RJ)", 
    "2": "Guri (SP)", 
    "3": "Prado (SP)", 
    "4": "Brennuz (SP)", 
    "5": "Magrão (SP)", 
    "6": "Japa (BA)", 
    "7": "Bask (SP)", 
    "8": "Alves (DF)", 
    "9": "Nonô (DF)", 
    "10": "Balota (DF)", 
    "11": "Neo BXD (RJ)", 
    "12": "Hate (DF)", 
    "13": "Zen (DF)", 
    "14": "Jeffe (DF)", 
    "15": "Pedog (DF)", 
    "16": "Renanzin (SP)", 
    "17": "Black Jay (SP)", 
    "18": "Levinsk (SP)", 
    "19": "Mikezin (SP)", 
    "20": "Bob 13 (SP)", 
    "21": "Saboó (SP)", 
    "22": "Youngui (SP)", 
    "23": "THM (SP)", 
    "24": "Zuluzão (SP)", 
    "26": "Dubaile (SP)", 
    "27": "Xamuel (SP)", 
    "28": "Maria (SP)", 
    "29": "Baueb (SP)", 
    "30": "Killua (SP)", 
    "31": "Kant (SP)", 
    "32": "Jotapê (SP)", 
    "33": "Gine (RJ)", 
    "34": "Schuler (RJ)", 
    "35": "Mineiro (RJ)", 
    "36": "Dubaile (RS)", 
    "37": "Grafiteh (SP)", 
    "38": "MT (RJ)", 
    "39": "Lux D (RJ)", 
    "40": "Kroy (SP)", 
    "41": "Tavin (SP)", 
    "42": "Lili (SP)", 
    "43": "Lil Vi (SP)", 
    "44": "Noventa (ES)", 
    "45": "Dherik (SP)", 
    "46": "Apollo (SP)", 
    "47": "Barreto (SP)", 
    "48": "ASP (RJ)", 
    "49": "Yori DS (RJ)", 
    "50": "Moita Treta (SP)", 
    "51": "Devilzinha (RJ)", 
    "52": "Alê (RJ)", 
    "53": "Moita Treta (RJ)", 
    "54": "Dandinho (SP)", 
    "55": "NLE Dopre (SP)", 
    "56": "Vitu (PE)"
};