// [AUTO-GENERATED FILE] -> Do not modify

allMcNames = [
    "Tubarão (SP)", 
    "Jhony (RJ)", 
    "Guri (SP)", 
    "Prado (SP)", 
    "Brennuz (SP)", 
    "Magrão (SP)", 
    "Japa (BA)", 
    "Bask (SP)", 
    "Alves (DF)", 
    "Nonô (DF)", 
    "Balota (DF)", 
    "Neo BXD (RJ)", 
    "Hate (DF)", 
    "Zen (DF)", 
    "Jeffe (DF)", 
    "Pedog (DF)", 
    "Renanzin (SP)", 
    "Black Jay (SP)", 
    "Levinsk (SP)", 
    "Mikezin (SP)", 
    "Bob 13 (SP)", 
    "Saboó (SP)", 
    "Youngui (SP)", 
    "THM (SP)", 
    "Zuluzão (SP)", 
    "Dubaile (SP)", 
    "Xamuel (SP)", 
    "Maria (SP)", 
    "Baueb (SP)", 
    "Killua (SP)", 
    "Kant (SP)", 
    "Jotapê (SP)"
];